set-option -g default-shell /usr/bin/zsh
set-option -g default-command /usr/bin/zsh
set -g allow-passthrough on

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Plugins
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'

set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# Continuum
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

set -g @sessionx-bind 'o'
set -g @sessionx-custom-paths '~/Codes'

set -g status-left '#{prefix_highlight} | %H:%M'

# Keep this line at the very bottom
run '~/.tmux/plugins/tpm/tpm'
